---
title: "map"
author: "rj2543"
date: "May 8, 2019"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)
library(tidyverse)
```

```{r}
italy = map_data("italy")
head(italy)
```

```{r}
ggplot() + 
  geom_polygon(data = italy, 
               aes(x = long, y = lat, group = group),
               color = "white") + # without color, no grouping
  coord_fixed(1.3)
```

```{r}
ggplot() + 
  geom_polygon(data = italy,
               aes(x = long, y = lat, group = group, fill = region),
               color = "white") + 
  coord_fixed(1.3) + 
  guides(fill = FALSE) # without, legend should be too big
```

```{r}
italian_cities = tibble(lat = c(43.769562, 41.902782, 45.438759),
                        long = c(11.255814, 12.496366, 12.327145),
                        names = c("Florence", "Rome", "Venice"))

ggplot() + 
  geom_polygon(data = italy,
               aes(x = long, y = lat, group = group, fill = region),
               color = "white") + 
  coord_fixed(1.3) + 
  guides(fill = FALSE) +
  geom_point(data = italian_cities, aes(x = long, y = lat), color = "grey15", size = 1.5)
```

```{r}
ggplot() + 
  geom_polygon(data = italy,
               aes(x = long, y = lat, group = group, fill = region),
               color = "white") + 
  coord_fixed(1.3) +
  guides(fill = FALSE) +
  geom_label(data = italian_cities,
             aes(x = long, y = lat, label = names), 
             size = 2)
```

```{r}
ggplot() + 
  geom_polygon(data = italy,
               aes(x=long, y = lat, group = group),
               color = "white", fill = "gray68") + 
  coord_fixed(1.3) + 
  guides(fill = FALSE) +
  geom_point(data = italian_cities,
             aes(x = long, y = lat), 
             color = "grey15",
             size = 1.5) +
  geom_text(data = italian_cities,
            aes(x = long, y = lat + 0.35, label = names), 
            size = 3)
```

```{r}
italian_cities_density = read_csv("provinces_italy.csv") %>% 
  janitor::clean_names() %>% 
  rename(subregion = province)

head(italian_cities_density)

other.regions = c("Agrigento","Trapani","Messina","Palermo",
                   "Caltanissetta", "Udine","Pordenone","Gorizia", "Venezia",
                   "Trieste",  "Milano",   "Padova",   "Torino",  "Mantova",
                   "Genova",   "Massa-Carrara", "Forli'", "Firenze",  
                   "Pesaro e Urbino", "Arezzo",   
                   "Livorno", "Grosseto", "Sassari",  
                   "Avellino", "Latina",  "Napoli", "Cagliari")

italy = italy %>%
            mutate(subregion = ifelse(is.na(subregion),
                                            region,
                                            subregion),
                   subregion = ifelse(region %in% other.regions, 
                                      region,
                                      subregion)) %>%
            left_join(italian_cities_density, "subregion")
```

```{r}
ggplot() + 
  geom_polygon(data = italy,
               aes(x=long, y = lat, group = group, fill = density),
               color = "white") + 
  coord_fixed(1.3) + 
  scale_fill_gradient(trans = "log10")
```

```{r}
ggplot() + 
  geom_polygon(data = italy,
               aes(x = long, y = lat, group = group, fill = administrative),
               color = "white") +
  coord_fixed(1.3)
```

```{r}
ggplot() + 
  geom_polygon(data = italy,
               aes(x = long, y = lat, group = group, fill = macro),
               color = "white") + 
  coord_fixed(1.3) +
  theme_nothing()
```

```{r}
ggplot() + 
  geom_polygon(data = italy,
               aes(x=long, y = lat, group = group, fill = macro),
               color = "white") + 
  coord_fixed(1.3) +
  xlim(12.5,20) + ylim(37.5, 43) +
  theme_bw()
```

```{r}
ggplot() + 
  geom_polygon(data = italy, aes(x=long, y = lat, group = group, fill = macro),
               color = "white") + 
  coord_fixed(xlim = c(12.5,20),  ylim = c(37.5, 43), ratio = 1.3) +
  xlab("Longitude") + ylab("Latitude") +
  theme_classic()
```

